- name: copyModule
  hosts: tomcat
  become: true
  tasks:
   - name: copying the war file.
     ansible.builtin.copy:
       src: /var/lib/jenkins/workspace/myekspipelinejob/target/springbootApp.jar
       dest: /opt/tomcat/webapps
